### ISSUE TITLE
Interfaces

### ISSUE THREAD

**Issue by Gutzon** [MercantecData/portfolio-Gutzon#4]
Jeg kunne godt tænke mig nogle bedre exempler på brugen af interfaces end det der er på Microsoft.

Forstår ikke helt hvordan man skal løse denne:
Lav et interface med 3 metoder i. Implementer interfacet i klasserne fra første opgave.

**Comment by MadsBock** [comment]
Jeg er heller ikke helt sikker på hvad jeg mente med den. Nå jeg omformulerer den så.

 - Lav et interface med 3 metoder i. Implementer dette interface i 2 forskellige classes. 

Hvad for nogle funktioner det er er underordnet.

Interfaces bruges til at tillægge funktionalitet til en class uden at bruge nedarving. Den store forskel på det og nedarving er at en class kun kan nedarve fra én superclass. Men den kan implementere et hvilket som helst antal interfaces. Ligesom med nedarving er der tale om at man tilføjer typer til sit objekt, hvilket vil sige at hvis en class eksempelvis implementerer et interface "IComparable", så vil et objekt af denne class kunne gemmes i en variabel af typen IComparable.

**Comment by Gutzon** [comment]
Jeg tror du misseede noget i Readme dokumentet

**Comment by MadsBock** [comment]
Uddyb?
